# Generated by Django 3.0.1 on 2020-01-01 06:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invitations',
            new_name='Invitation',
        ),
    ]
